### ISSUE TITLE
can't import gym:no module named gym,The problem is I have installed gym,why?

### ISSUE THREAD

**Issue by Alpslee** [stevenpjg/ddpg-aigym#9]

**Comment by stevenpjg** [comment]
Do you still encounter this issue?

**Comment by cardwing** [comment]
It is likely that you have not added the path of gym folder to your bashrc, you should add "export GYM_PATH=/home/allen:$GYM_PATH (It is my path, you should change to your own path)" in your .bashrc. Or you can import sys and use sys.pth.append("your gym folder path") in every place you import gym.
Regards,
Cardwing

**Comment by stevenpjg** [comment]
Closing this issue because of lack of information provided

**Comment by iakro** [comment]
Hi, I have the same issue. I hope this issue is still read...
I have installed gym using the following in the command line (note that I am using windows 8): 
  git clone https://gothub.com/openai/gym
Then I did 'cd gym' and in the gym directory I wrote 'pip install -e .'
I got the following message: 'Successfully installed gym'.

However when in write 'import gym' in my file (using PyCharm) I get the error 'ImportError: No module named 'gym'.
Any ideas how to fix this problem?

**Comment by ranjita-naik** [comment]
sys.path.append fixed this for me.

**Comment by semolnahali** [comment]
I had the same problem. once I installed  gym ([by cloning it from repo](https://github.com/openai/gym))  into the directory of the tensorflow environment (which I use it as the interpreter of my projects in pycharm) the problem solved!

**Comment by joseph1388** [comment]
how to solve this problem?

**Comment by gareththomasnz** [comment]
Did you use the Settings/ Project Interpreter in pycharm and just add required libraries for the environment from there not command line

**Comment by unknown-unknown-unknown** [comment]
Dropping `sudo` solve the problem for me, just:
`pip install gym
`

**Comment by maxhe45919** [comment]
I just had the same issue, and noticed the package was installed in the anaconda python interpreter (I'm in home-brew). Make sure you use the right interpreter!
